from app.models.user import User
from app.models.patient import Patient
from app.models.symptom import Symptom
from app.models.patient_symptom import PatientSymptom
from app.models.medical_history import MedicalHistory
from app.models.medication import Medication
from app.models.allergy import Allergy
from app.models.diagnostic_session import DiagnosticSession
from app.models.vitals import Vitals
from app.models.lab_result import LabResult
from app.models.ai_assessment import AIAssessment
from app.models.diagnosis import Diagnosis
from app.models.session_diagnosis import SessionDiagnosis
from app.models.follow_up_question import FollowUpQuestion